### ISSUE TITLE
.AlarmClockService.ListAndParseAlarms()   throws error (in case no alarms are set)

### ISSUE THREAD

**Issue by hklages** [svrooij/node-sonos-ts#104]
If there are no alarms the following error is thrown: 

```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'Duration' of undefined
    at C:\Users\hekla\Development\node-red-contrib-sonos-events\node_modules\@svrooij\sonos\lib\services\alarm-clock.service.extension.js:32:33
    at Array.forEach (<anonymous>)
    at AlarmClockService.ListAndParseAlarms (C:\Users\hekla\Development\node-red-contrib-sonos-events\node_modules\@svrooij\sonos\lib\services\alarm-clock.service.extension.js:30:16)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async EventEmitter.sendAlarmClockMessage (C:\Users\hekla\Development\node-red-contrib-sonos-events\src\sonosevents-household.js:80:22)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:34032) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:34032) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by svrooij** [comment]
What do you think is the best solution?

Check if there are alarms and then throw a "No alarms defined" error or just return an empty array?

**Comment by hklages** [comment]
Usually I prefer to receive the same type - ergo: empty array.
