### ISSUE TITLE
BUG: Spotify playlist Zu Hause throws an error. 

### ISSUE THREAD

**Issue by hklages** [svrooij/node-sonos-ts#137]
### What happened

Queuing a spotify playlist throws an error. Playlist is valid Zu Hause

### What did you expect to happen

Members of that playlist to be added to SONOS queue

### How to reproduce it (minimal and precise)

command: AddUriToQueue
Playlist: spotify:user:spotify:playlist:37i9dQZF1DX1htCFhfVtyK

### Debug logging

```
"group.queue.urispotify:Sonos error on AddURIToQueue UPnPError 804 (undefined) :: Details: {"stack":"SonosError: Sonos error on AddURIToQueue UPnPError 804 (undefined)
 at AVTransportService.handleErrorResponse (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-sonos-plus/node_modules/@svrooij/sonos/lib/services/base-service.js:231:23)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async AVTransportService.handleRequestAndParseResponse (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-sonos-plus/node_modules/@svrooij/sonos/lib/services/base-service.js:204:15)
at async AVTransportService.SoapRequestWithBody (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-sonos-plus/node_modules/@svrooij/sonos/lib/services/base-service.js:97:16)
at async AVTransportService.AddURIToQueue (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-sonos-plus/node_modules/@svrooij/sonos/lib/services/av-transport.service.js..."
```

### Environment

- sonos-ts version: 2.4.0

### Checklist

Please confirm the following before creating the issue.

- [x] Environment specified
- [x] Checked [issues](https://github.com/svrooij/node-sonos-ts/issues?q=is%3Aissue) for duplicates
- [x] Debug log added

**Comment by svrooij** [comment]
The URL isn't correct.....

All spotify urls I've seen are in the following format `spotify:{kind}:{id}` all the supported urls are tested [here](https://github.com/svrooij/node-sonos-ts/blob/08198914ab7b09eec2350c59a3bf08cd8e207c03/tests/helpers/metadata-helper.test.ts#L168)

The guessing of meta data is described [here](https://sonos-ts-beta.svrooij.io/sonos-device/methods.html#metadata)

**Comment by hklages** [comment]
That format used to work but now also your example does not work anymore (from old node - sonos)

Have to explore more. 

![spotify playlists](https://user-images.githubusercontent.com/17273119/118642036-29af3080-b7db-11eb-980e-67348e93c82d.png)

**Comment by svrooij** [comment]
I think the sample was incorrect, there is no code to parse that url and generate metadata.
The code is mainly copied and improved upon from the old library.

**Comment by hklages** [comment]
Could it be that your test case works because a "c" is missing after the 206 and before "spotify" 

Are you able to play that playlist on your player? 

![missingC](https://user-images.githubusercontent.com/17273119/118700843-5e3ede80-b813-11eb-867c-55333bf2bc12.png)

**Comment by hklages** [comment]
confirmation: beta-.3 fixes that issue. 

My 5 test cases  (album, track, toptrack AND playlist) works fine and add the tracks to the queue.
