### ISSUE TITLE
BUG: Sonos error on GetZoneGroupState UPnPError 501

### ISSUE THREAD

**Issue by kacbrz** [svrooij/node-sonos-ts#198]
### What happened

When I add more than 17 Sonos AMPs (devices) into my Sonos ecosystem then I can't use sonos2mqtt.

### What did you expect to happen

There should be option to add more than 17 Sonos AMPs, otherwise I can't fully enjoy my audio system 😄.

### How to reproduce it (minimal and precise)

1. Buy more than 17 AMps...
2. Bring them home and install whole system.
3. Be mad about Sonos AMPs "virtual" limit.

I am aware that my case might be the only one. Nevertheless I hope that some good soul could help me out with this issue.

### Debug logging

```plain
household.create.group:Sonos error on GetZoneGroupState UPnPError 501 (Action failed) :: Details: {"stack":"SonosError: Sonos error on GetZoneGroupState UPnPError 501 (Action failed)\n    at ZoneGroupTopologyService.handleErrorResponse (/data/node_modules/@svrooij/sonos/lib/services/base-service.js:242:23)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at ZoneGroupTopologyService.handleRequestAndParseResponse (/data/node_modules/@svrooij/sonos/lib/services/base-service.js:215:15)\n    at ZoneGroupTopologyService.SoapRequest (/data/node_modules/@svrooij/sonos/lib/services/base-service.js:89:16)\n    at ZoneGroupTopologyService.GetZoneGroupState (/data/node_modules/@svrooij/sonos/lib/services/zone-group-topology.service.js:44:40)\n    at getGroupsAll (/data/node_modules/node-red-contrib-sonos-plus/src/Commands.js:529:29)\n    at Object.householdCreateGroup [as household.create.group] (/data/node_modules/node-red-contrib...
```

### Environment

- sonos-ts version: latest
- OS: Dockerized - ghcr.io/svrooij/sonos2mqtt
- node version (`node -v`): not sure what version of nodejs is inside that Docker

### Checklist

Please confirm the following before creating the issue.

- [x] Environment specified
- [x] Checked [issues](https://github.com/svrooij/node-sonos-ts/issues?q=is%3Aissue) for duplicates
- [x] Debug log added

**Comment by svrooij** [comment]
What version of sonos2mqtt are you using?

There is code available for this exact use case (which I've heard about before and build a theoretical fix for)

https://github.com/svrooij/node-sonos-ts/blob/beta/src%2Fsonos-manager.ts#L62

I think this version should no longer have that issue https://github.com/svrooij/sonos2mqtt/releases/tag/v3.2.0-beta.19

Otherwise I need 7 extra speakers to be able to reproduce this issue, shall I create a go fund me?

**Comment by kacbrz** [comment]
@svrooij Wow, thanks for replying so fast. First of all, thank you very much for creating and maintaining sonos2mqtt and node-sonos-ts.

I can't say right now what exact version it is, but I will check it and get back to you. After that I will also check out the release you've shared.

Probably it would be cheaper to accommodate you in my place in Warsaw :)

**Comment by svrooij** [comment]
@kacbrz any luck?
