### ISSUE TITLE
UnhandledPromiseRejection

### ISSUE THREAD

**Issue by hklages** [svrooij/node-sonos-ts#81]
```
(node:16948) UnhandledPromiseRejectionWarning: Error: No subscription id received
    at RenderingControlService.subscribeForEvents (C:\Users\hekla\Development\node-red-contrib-sonos-events\node_modules\@svrooij\sonos\lib\services\base-service.js:298:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async EventEmitter.<anonymous> (C:\Users\hekla\Development\node-red-contrib-sonos-events\node_modules\@svrooij\sonos\lib\services\base-service.js:280:21)
(node:16948) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)

```

Maybe because the `await this.subscribeForEvents()` is not in an async function?

**Comment by svrooij** [comment]
When does this happen?
I need a bit more detail about the players, how come it isn’t available?

**Comment by hklages** [comment]
Thanks!
