### ISSUE TITLE
UnhandledPromiseRejectionWarning - in case the sonos player is not available

### ISSUE THREAD

**Issue by hklages** [svrooij/node-sonos-ts#82]
```
(node:23976) UnhandledPromiseRejectionWarning: FetchError: request to http://192.168.178.37:1400/MediaRenderer/AVTransport/Event failed, reason: connect EHOSTUNREACH 192.168.178.37:1400
    at ClientRequest.<anonymous> (C:\Users\hekla\Development\node-red-contrib-sonos-events\node_modules\node-fetch\lib\index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:486:12)
    at Socket.socketErrorListener (_http_client.js:469:9)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:486:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:23976) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:23976) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by svrooij** [comment]
Related to #81

**Comment by hklages** [comment]
Thanks again :-)

**Comment by svrooij** [comment]
I would like to keep the issue open until it is auto closed by the release to production. That way everybody not using the beta still see what issues exists (and are maybe already fixed in a beta).

**Comment by hklages** [comment]
Understand.
